import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
// import styles from '../styles/Home.module.css'
import Slideshow from "../component/slideShow" 
import Testimonial from "../component/testimonial" 
import {  Stack, Typography, Box } from '@mui/material';  
import Service from "../public/Service.png"
import Homes from "../public/Homes.jpg"
import Big from "../public/Big.jpg"
import Client from "../public/client.png"
import Contact from "../public/contact.jpg"
import Staff from "../public/staff.png"
// import DrawerAppBar from "../component/majAppbar"
import ElevationScroll from "../component/minAppbar"
import Footer from "../component/footer"
import Footer2 from "../component/footer2"
import TextField from '@mui/material/TextField'
import Button from '@mui/material/Button'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Fidelitinvestment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Slideshow />
     {/* <DrawerAppBar /> */}
     <ElevationScroll />

     <Stack
  direction="column"
  justifyContent="center"
  alignItems="center"
  mt={10}>
    
    <Typography variant='h4' sx={{fontFamily: "Quicksand"}}>We Are Invetex...</Typography>

    <Typography textAlign="center" sx={{fontFamily: "Quicksand"}}>First U.S. institutional asset manager focused exclusively on blockchain technology.<br />
Since 2013, sterling Assets has invested in digital assets, agriculture and blockchain<br />
 companies, providing investors with the full spectrum of exposure to the space..</Typography>
  </Stack>

  <Stack
  direction={{xs: "column", md: "row"}}
  justifyContent="center"
  alignItems="center"
  spacing={8}
  mt={5}
>
  <Box >
    <Stack
  direction="row"
  justifyContent="center"
  alignItems="center"
  spacing={6}
  mt={10}
>

    <Image src="/service_04.png" width={150} height={120} alt="" />
</Stack>
<Typography textAlign="center" style={{fontWeight: "600"}} mt={-3} >Market Forecasting</Typography>
<Typography textAlign="center" mt={2} mb={2} style={{color: "lightgray"}} >Market-leading experience and services</Typography>
<Typography textAlign="center" style={{color: "#757575"}} >Preparation of detailed company <br />
  specific models used for decision <br />
  making purposes</Typography>
  </Box>
  <Box >
    <Stack
direction={{xs: "column", md: "row"}}
  justifyContent="center"
  alignItems="center"
  spacing={6}
  mt={10}
>

    <Image src="/service_05.png" width={150} height={120} alt="" />
</Stack>
<Typography textAlign="center" style={{fontWeight: "600"}} mt={-3} >Financial Modeling</Typography>
<Typography textAlign="center" mt={2} mb={2} style={{color: "lightgray"}} >Market-leading experience and services</Typography>
<Typography textAlign="center"  style={{color: "#757575"}} >Preparation of detailed company<br />
 specific models used for decision<br />
  making purposes</Typography>
  </Box>
   <Box >
    <Stack
  direction="row"
  justifyContent="center"
  alignItems="center"
  spacing={6}
  mt={10}
>

    <Image src="/service_06.png" width={150} height={120} alt="" />
</Stack>
<Typography textAlign="center" style={{fontWeight: "600"}} mt={-3} >Financial Analysis</Typography>
<Typography textAlign="center" mt={2} mb={2} style={{color: "lightgray"}} >Market-leading experience and services</Typography>
<Typography textAlign="center"  style={{color: "#757575"}} >Assessment of viability, stability and
<br /> profitability
 of a business,<br /> sub-business or project</Typography>
  </Box>
</Stack>

<Box style={{backgroundColor: "lightgray"}}>
 <Stack 
  direction={{xs: "column"}}
  justifyContent="center"
  alignItems="center"
  mt={20}
  p={5}>
    
    <Typography fontSize={{xs: "20px", md: "40px"}} style={{fontWeight: "500"}}
      textAlign="center" variant='h4' sx={{fontFamily: "Quicksand"}}>WHO WAS STERLING ASSETS CREATED FOR?</Typography>

    <Typography textAlign="center" sx={{fontFamily: "Quicksand"}}>Economic services provided by the finance industry, which encompasses a broad<br />
range of businesses that manage money, including credit unions.</Typography>
  </Stack>

  <Stack 
  direction={{xs: "column", md: "row"}}
  justifyContent="center"
  alignItems="center"
  spacing={10}
  mt={-3}
  p={12}
>
  <Box >

    <Image src="/Homes.jpg" width={300}  height="250"  alt="/" />
    <Typography mt={-3} style={{fontSize: "30px", fontWeight: "600", color: "#795548"}}>01</Typography>


<Typography sx={{fontFamily: "Quicksand"}} >For individuals successfully operating<br/> in the
   field of investment, economics,<br /> business and finance,
   who want to<br /> create a zone of support, mentoring<br />
  
</Typography>
  </Box>
 
   
   <Box >

   <Image src="/Home2.jpg" width={300}  height="250"  alt="/" />
   <Typography mt={-3} style={{fontSize: "30px", fontWeight: "600", color: "#795548"}}>02</Typography>

<Typography sx={{fontFamily: "Quicksand"}}  >For entrepreneurs developing their
   own<br /> business who want to broaden their <br />knowledge of personal 
  finance and investments 
  </Typography>
  </Box>
  <Box >

  <Image src="/Home3.jpg" width={300}  height="250"  alt="/" />
  <Typography  mt={-3} style={{fontSize: "30px", fontWeight: "600", color: "#795548"}}>03</Typography>

<Typography sx={{fontFamily: "Quicksand"}} >For individuals interested in building their<br /> own financial independence,
   and entrepreneurs <br/>
    hoping to start a business but have inadequate fund for a startup</Typography>
  </Box>
 
</Stack>
</Box>


        {/* <Stack
  direction={{xs: "column", md: "row"}}
  justifyContent="center"
  alignItems="center"
  spacing={0}
  mt={-0.8}
  
>     
  <Box style={{backgroundColor: "gray"}} width={{xs:"100%", md: "27%"}} pt={10} pb={10}>
    <Stack
  direction="row"
  justifyContent="center"
  alignItems="center"
 
>

    <Image src={Service} width={100} alt="" />
</Stack>
<Typography textAlign="center" >Market Forecasting</Typography>
<Typography textAlign="center" >Market-leading experience and services</Typography>
<Typography textAlign="center" >Preparation of detailed company <br />
  specific models used for decision <br />
  making purposes</Typography>
  </Box>
  <Box style={{backgroundColor: "#EADDCA"}} width={{xs:"100%", md: "25%"}} pt={10} pb={10}>
    <Stack
direction={{xs: "column", md: "row"}}
  justifyContent="center"
  alignItems="center"
 
>

    <Image src="/Service.png" width={100} height={100} alt="" />
</Stack>
<Typography textAlign="center" >Market Forecasting</Typography>
<Typography textAlign="center" >Market-leading experience and services</Typography>
<Typography textAlign="center" >Preparation of detailed company <br />
  specific models used for decision <br />
  making purposes</Typography>
  </Box>
   <Box style={{backgroundColor: "#343434"}} width={{xs:"100%", md: "25%"}} pt={10} pb={10}>
    <Stack
  direction="row"
  justifyContent="center"
  alignItems="center"
 
>

<Image src="/Service.png" width={100} height={100} alt="" />
</Stack>
<Typography textAlign="center" >Market Forecasting</Typography>
<Typography textAlign="center" >Market-leading experience and services</Typography>
<Typography textAlign="center" >Preparation of detailed company <br />
  specific models used for decision <br />
  making purposes</Typography>
  </Box>
   <Box style={{backgroundColor: "black", color: "white"}} width={{xs:"100%", md: "25%"}} pt={10} pb={10}>
    <Stack
  direction="row"
  justifyContent="center"
  alignItems="center"
 
>

<Image src="/Service.png" width={100} height={100} alt="" />
</Stack>
<Typography textAlign="center" >Market Forecasting</Typography>
<Typography textAlign="center" >Market-leading experience and services</Typography>
<Typography textAlign="center" >Preparation of detailed company <br />
  specific models used for decision <br />
  making purposes</Typography>
  </Box>
</Stack> */}


<Testimonial />


<Stack
          px={{ xs: "4.80vw", md: "0" }}
          pl={{ md: "2.78vw" }}
          direction={{ xs: "column-reverse", md: "row" }}
          alignItems={"center"}
          mt={{xs: "10px"}}
          // justifyContent={{xs:"flex-start",}}
          spacing={{ xs: "0.00vw", md: "3.99vw" }}
        >
          <Box   maxWidth={{ md: "43.54vw" }}>
            <Typography  style={{fontFamily: "Quicksand", fontWeight: "500"}}
             fontSize={{xs:"38px", sm:"60px", md:"5.25vw"}} variant="h1">
            Invest in what <br />
           you believe in.
            </Typography>
            <Typography mt={2}  style={{fontFamily: "Quicksand", fontWeight: "500"}}
             fontSize={{xs:"28px", sm:"40px", md:"2.25vw"}} variant="h4">OUR ACTIVITIES
</Typography>
<Typography sx={{fontFamily: "Quicksand"}}>Training, seminars and workshops in two main streams - personal finance and investing as well as
    entrepreneurship and developing your own business using the latest trends and expert knowledge</Typography>
    <Typography mt={5} sx={{fontFamily: "Quicksand"}}>Consultations with a permanent group of experts of the Club , during which project
       participants will have the opportunity to gain knowledge about the financial market and  the possibility of investing savings 
      through investments on the stock exchange and in other areas such as real estate, luxury goods, art market</Typography>
           

            <Stack
              direction="row"
              my={{ xs: "14px", sm: "22px", md: "2.29vw" }}
              px={{xs:"50px", sm:"80px", md:"8.33vw"}}
              flexWrap={"wrap"}
              alignItems="center"
              spacing={{ xs: "4px", sm: "7px", md: "10px" }}
            >
              
            </Stack>
          </Box>
          <Box pl={{md:"6.60vw"}}  sx={{display: {xs: "none", md: "block"} }}
          maxWidth={{ md: "50.54vw" }}  width="100%">
            <Image src="/productImg4.jpg" alt="heroImage" width={665} height={550} />
          </Box>
        </Stack>
        {/* <Stack
  direction={{xs: "column"}}
  justifyContent="center"
  alignItems="center"
  mt={20}>
    
    <Typography  textAlign="center" variant='h4'>Our staff</Typography>

    <Typography textAlign="center"> 
    We work to make your business start effectively working for you.<br />
Meet the financial and marketing specialists.</Typography>


  </Stack>
  <Stack spacing={15}
  mt={5}
  mb={5}
  direction={{xs: "column", md: "row"}}
  justifyContent="center"
  alignItems="center">
    <Box>

  <Image src="/Staff.png"  width={300} height={300}  alt="" />
  <Typography mt={5} textAlign="center">Steven Monroe</Typography>
  <Typography textAlign="center">Marketing & Advertising</Typography>
    </Box>
  
    <Box>

<Image src="/Staff.png"  width={300} height={300}  alt="" />
<Typography mt={5} textAlign="center">Steven Monroe</Typography>
  <Typography textAlign="center">Marketing & Advertising</Typography>
  </Box>
  <Box>

  <Image src="/Staff.png"  width={300} height={300}  alt="" />
  <Typography mt={5} textAlign="center">Steven Monroe</Typography>
  <Typography textAlign="center">Marketing & Advertising</Typography>
    </Box>

  </Stack> */}
  {/* <Stack
         
          direction={{ xs: "column", md: "row" }}
          alignItems={"center"}
          mt={{xs: "60px"}}
         
          // justifyContent={{xs:"flex-start",}}
        
        >
          <Box   
          maxWidth={{ md: "55vw" }}  width="100%">
            <Image src="/Gold.png" width={600} height={600} alt="heroImage"   />
          </Box>
          <Box  mt={-10} maxWidth={{ md: "43.54vw" }}>
            <Typography  textAlign="center" style={{fontFamily: "Raleway", fontWeight: "500"}}
             fontSize={{xs:"28px", sm:"40px", md:"3.25vw"}} variant="h1">
        Request a Free Consultation

            </Typography>

            <Typography textAlign="center">
            Perspiciatis unde omnis iste natus sit voluptatem accusantium doloremque.
            </Typography>
            <Stack mt={5} direction={{xs: "column", md: "row"}} p={2}
            spacing={5}>
              <TextField label="name*"/>
              <TextField  label="email*"/>
              
            </Stack>
            <Stack mt={2} direction={{xs: "column", md: "row"}} p={2}
            spacing={5}>
              <TextField label="phone"/>
              <TextField label="subject" />
             
            </Stack>
            <Stack  p={2}>

           <textarea style={{width: "100%", padding: "50px", marginTop: "20px"}}
           placeholder="message"
           ></textarea>
            </Stack>
           <Stack
           justifyContent="center"
           alignItems="center"
           pr={5}>

           <Button style={{backgroundColor: "lightgreen", color: "white"}}>Send Request</Button>
           </Stack>
           
          </Box>
        </Stack> */}
        <Stack
  direction={{xs: "column"}}
  justifyContent="center"
  alignItems="center"
  mt={20}>
    
    <Typography  textAlign="center" variant='h4'>Our Goals</Typography>

    <Typography textAlign="center"> 
    Educating through access to the latest knowledge, contact< br/> with experts and
    creating space for learning,integration,exchange of experiences and establishing relationships.</Typography>


  </Stack>
  <Stack
  direction={{xs: "column", md: "row"}}
  justifyContent="center"
  alignItems="center"
  spacing={5}
  textAlign="center"
  mt={10}
  mb={5}
  >
<Typography sx={{fontFamily: "Quicksand"}}>Inspiring individuals to actively make decisions in <br />areas of investing and securing the future.</Typography>
<Typography sx={{fontFamily: "Quicksand"}}>Supporting individual's enterpreneurship and <br />developing competence in safe investing and running a business.</Typography>
<Typography sx={{fontFamily: "Quicksand"}}>Creating a safe space for learning, integration, exchange of<br /> experiences and establishing professional and personal relationships.</Typography>
{/* <Typography sx={{fontFamily: "Quicksand"}}>Creating a safe<br /> investment platform for individuals and institutions.</Typography> */}
<Typography sx={{fontFamily: "Quicksand"}}>Inspiring individuals to actively make decisions in the  <br />area of investing and securing the future.</Typography>

  </Stack>
  
<Footer2 />
    </>
  )
}
